sudo: false
notifications:
  irc: "chat.freenode.net#horde"
language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
before_script:
  - export MAILAUTOCONFIG_TEST_CONFIG='{"mail_autoconfig":{"nonauth_emails":["test@gmail.com","test@gmx.net"],"nonauth_emails_bad":["test@example.com"],"domains":[[["gmail.com"]],[["test.mail.gmail.com","mail.gmail.com","gmail.com"]]]}}';
  - phpenv config-rm xdebug.ini || echo "XDebug not enabled"
  - pear install channel://pear.horde.org/Horde_Test
  - pear install package.xml
script:
  - php $(find test -name AllTests.php)
